language: csharp
mono: none
dotnet: 2.1.502

addons:
  sonarcloud:
    organization: "kv"

before_install:
- bash ./.tools/travis-ci-install-sonar.sh
install:
- dotnet restore
script:
- bash ./.tools/travis-ci-build.sh

cache:
  directories:
    - '$HOME/.nuget/packages'
    - '$HOME/.local/share/NuGet/Cache'
    - '$HOME/.sonar/cache'